# Setup
title:               IFT6758 Hockey Project
tagline:             'Project Milestone Blog'
#description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:         'Gaining experience with the data wrangling and exploratory data analysis phases of a data science project.'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Sara E., Tim L., Jake W.
  url:               
  email:             sara.elkafrawy@gmail.com , timothykolee@gmail.com , jwhite2217@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
